fix(urlencode): urlencode CIRCLE_BRANCH
eddiewebb/circleci-queue pull request #90
Opened 2022-11-29 18:23 UTC by andrew-barnett

### Motivation, issues

The CircleCI API (started?) requiring urlencoded branch names, otherwise the calls were returning empty results. This caused the queue to never succeed. This fix urlencodes the branch name. See #89

### Description

add `urlencode` function and run `${CIRCLE_BRANCH}` through it while building branch-specific API url

fixes #89

2022-12-01 11:12 UTC, eddiewebb commented
bors try

2022-12-01 11:21 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:417`

2022-12-01 14:23 UTC, eddiewebb commented
bors delegate+

2022-12-01 14:24 UTC, eddiewebb commented
@andrew-barnett - please see my comment/concern about portability.  Assuming it works across those 3 shells I have delegated review permission, so you can just add a comment here of `bors merge`

2022-12-02 20:39 UTC, andrew-barnett commented
@eddiewebb I'm not finding your comment about which shells to check. Can you post here?

2022-12-03 00:49 UTC, eddiewebb requested changes

2022-12-03 00:49 UTC, eddiewebb commented on src/commands/until_front_of_line.yml
> +        urlencode(){
@andrew-barnett - how much of this is specific on a shell (bash, zsh, ash)? Or is it portable?

2022-12-03 00:49 UTC, eddiewebb commented
I'm sorry Andrew it was stuck pending, submitted it.

2022-12-06 16:18 UTC, andrew-barnett commented
> @andrew-barnett - please see my comment/concern about portability. Assuming it works across those 3 shells I have delegated review permission, so you can just add a comment here of `bors merge`

@eddiewebb - It didn't work on zsh, so updated the code to make it portable. Passing it back for review.

2022-12-06 16:19 UTC, andrew-barnett commented
bors try

2022-12-06 16:28 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:421`

2022-12-06 16:48 UTC, andrew-barnett commented
bors r+

2022-12-06 16:58 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:424`

2022-12-06 23:28 UTC, eddiewebb commented
bors merge

2022-12-06 23:29 UTC, eddiewebb commented
( ialways get the magic PR title wrong, added a sanity check and changelog)

Version 1.8.2 and soon 1.8.3 wil include this fix, thanks @andrew-barnett !

2022-12-06 23:29 UTC, eddiewebb commented
bors merge

2022-12-06 23:38 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:431`

2022-12-06 23:39 UTC, eddiewebb commented
BotComment: *Production* version of orb available for use - `eddiewebb/queue@1.8.4`

2022-12-06 23:39 UTC, merged