Add custom hostname to support server customer use
eddiewebb/circleci-queue pull request #92
Opened 2023-02-09 06:42 UTC by nanophate

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

https://github.com/eddiewebb/circleci-queue/issues/91

This change will help server user to also use this orb on their own hosted server.

### Description

Replaced the `https://circleci.com` to use a pipeline parameters. 
Added pipeline parameter default to be `https://circleci.com` so that cloud customer would not get this impact.

2023-02-09 07:03 UTC, kelvintaywl reviewed
perhaps we can assume HTTPS is always to be used, so the parameter's default value can be just `circleci.com` rather than `https://circleci.com`

2023-02-09 11:28 UTC, eddiewebb commented
Thank you @nanophate , what a great addition.

I agree with @kelvintaywl , all CCI servers should still be behind HTTPS, and it is really the hostname we're adjusting.

Also, please add:
1) a sample config file using new value (see test/inputs)
2) a simple assertion test that loads that config (which itself just does replacemernt and validation) and if possible a simple assertion the output script contains a line matching the provided header.  https://github.com/eddiewebb/circleci-queue/blob/main/test/test_expansion.bats#L26-L36

2023-02-09 11:35 UTC, eddiewebb requested changes
Thank you so much. A few adjustments please, and In look forward to merging this.

2023-02-09 11:35 UTC, eddiewebb commented on src/commands/until_front_of_line.yml
>              echo "Using API key for user: ${me}"
worth updating `user: ${me}, host: << parameters.circleci-hostname >>`

2023-02-09 11:35 UTC, eddiewebb commented on src/commands/until_front_of_line.yml
> +    default: "https://circleci.com"
reduce to just host. we must assume https as best practice.

2023-02-09 11:35 UTC, eddiewebb commented on src/commands/until_front_of_line.yml
> +            jobs_api_url_template="<< parameters.circleci-hostname >>/api/v1.1/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}?filter=running"
Declare as BASH variable once near beginning (like https://github.com/eddiewebb/circleci-queue/blob/main/src/commands/until_front_of_line.yml#L47) and then use env_var thorugh script.

This was authored before support for `include` but I want to move that way ans so avoid as much inline parameters as possible for now.

`CIRCLECI_BASEURL="http://<< parameters.circleci-hostname >>"`
And that would be a great line to assert in the tests

2023-02-09 11:35 UTC, eddiewebb commented on src/jobs/block_workflow.yml
> +      circleci-hostname: <<parameters.circleci-hostname>>
especially given name says `host` we should update default and script to match.

2023-02-09 11:35 UTC, eddiewebb commented
bors try

2023-02-10 14:14 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:436`

2023-02-10 18:03 UTC, eddiewebb approved these changes

2023-02-10 18:03 UTC, eddiewebb commented
bors try

2023-02-10 18:12 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:442`

2023-02-10 20:08 UTC, eddiewebb commented
@nanophate - would you please try `eddiewebb/queue@dev:442` and report back your results?

2023-02-13 02:38 UTC, nanophate commented
@eddiewebb Thank you for updating the pr by adding test and suggested changes. I tested out the orb on server and it is working as expected!! Thankyou so much for checking this out 🙇 

https://app.gke-circleci.nanophate.com/pipelines/github/nanophate-cci/check-queue/11/workflows/5118df17-510f-49fd-9703-ca2f2bb9b18f/jobs/22?invite=true#step-101-276

https://github.com/nanophate-cci/check-queue/blob/main/.circleci/config.yml

![Screenshot 2023-02-13 at 11 35 50](https://user-images.githubusercontent.com/6015450/218358093-b5ce1b0b-1a49-4856-9dc6-ca0035415ac2.png)

```sh
Attempting to access CircleCI api. If the build process fails after this step, ensure your CIRCLECI_API_KEY  is set.
DEBUG: Making API Call to https://gke-circleci.nanophate.com/api/v1.1/project/github/nanophate-cci/check-queue/tree/main?filter=running
DEBUG: API Success
API access successful
Checking time of workflow: 5118df17-510f-49fd-9703-ca2f2bb9b18f
DEBUG: Making API Call to https://gke-circleci.nanophate.com/api/v2/workflow/5118df17-510f-49fd-9703-ca2f2bb9b18f
DEBUG: API Success
Workflow was created at: 2023-02-13T02:35:22Z
Checking time of workflow: 4c3d4fec-6272-4229-b305-fc02794a4b0f
DEBUG: Making API Call to https://gke-circleci.nanophate.com/api/v2/workflow/4c3d4fec-6272-4229-b305-fc02794a4b0f
DEBUG: API Success
Workflow was created at: 2023-02-13T02:35:08Z
Orb parameter block-workflow is false.
Only blocking execution if running previous jobs matching this job: deploy
Oldest job: 20
This Workflow Timestamp: "2023-02-13T02:35:22Z"
Oldest Workflow Timestamp: "2023-02-13T02:35:08Z"
This build (22) is queued, waiting for build number (20) to complete.
Total Queue time: 11 seconds.

```

2023-02-13 14:00 UTC, eddiewebb commented
bors merge

2023-02-13 14:09 UTC, eddiewebb commented
BotComment: *Development* version of orb available for manual validation - `eddiewebb/queue@dev:445`

2023-02-13 14:10 UTC, eddiewebb commented
BotComment: *Production* version of orb available for use - `eddiewebb/queue@1.12.0`

2023-02-13 14:10 UTC, merged

2023-02-13 14:14 UTC, eddiewebb commented
Wha the heck?  i thought this weould be 1.10...  Anyway its up as 1.12